### ISSUE TITLE
Bernoulli distribution for MNIST

### ISSUE THREAD

**Issue by gemoran** [FabianFalck/mfcvae#2]
Hi, I'm getting an error when running the MNIST example (I'm using torch version 1.12.1).

```
Traceback (most recent call last):
  File "<input>", line 637, in <module>
    log_prob_p_x_z = p_x_z.log_prob(x)  # e.g. torch.Size([8])
    log_prob = self.base_dist.log_prob(value)
    raise ValueError(
ValueError: Expected value argument (Tensor of shape (512, 784)) to be within the support (Boolean()) of the distribution Bernoulli(probs: torch.Size([512, 784])), but found invalid values:
```

I think it's because the torch.distributions.Bernoulli expects the MNIST data to be either 0 or 1, instead of in [0,1].

I replaced lines 426-431 in mfcvae.py with the following and the error goes away:

```        
# term 1: compute log p(x|z), the MC estimate of E_{q(z,c|x)}[log p(x|z)] where z~q(z|x)
if self.likelihood_model == 'Bernoulli':
    # p_x_z = D.Independent(D.Bernoulli(probs=torch.clamp(x_hat, min=1e-10, max=1-(1e-10))), 1)
    # log_prob_p_x_z = p_x_z.log_prob(x)  # e.g. torch.Size([8])
    # can't use D.Bernoulli here because x is continuous between [0,1]

    bernoulli_loss = torch.nn.BCELoss(reduction='none')
    log_prob_p_x_z = -torch.sum(bernoulli_loss(torch.clamp(x_hat, min=1e-10, max=1 - (1e-10)), x), axis=1)
elif self.likelihood_model == 'Gaussian':
    p_x_z = D.Independent(D.Normal(loc=x_hat, scale=torch.ones_like(x_hat) * self.sigma_multiplier_p_x_z), 1)
    log_prob_p_x_z = p_x_z.log_prob(x)  # e.g. torch.Size([8])
```

**Comment by FabianFalck** [comment]
Hi @gemoran , thanks for pointing this out! 

I remember this issue vaguely: In the version of PyTorch we used (0.8.2, see requirements.txt), log_prob computes something like (if not the same) as the BCELoss you are proposing as a fix. So your fix in the newer version looks good to me! But you are right: computing log probability of a Bernoulli expects {0,1} input, not a continuous value in [0,1], hence I presume this was changed in the more frequent version of PyTorch, and it is most definitely a wiser choice to compute the reconstruction as you did in the first place. 

I'd leave the code as is for now for reproducibility reasons, but your comment is spot on and shall help anyone with a newer version of PyTorch to fix this! -- Let me know if you can still reproduce our results with this fix, that would be good to know! :-)

**Comment by gemoran** [comment]
Sounds good, thank you!! Yes results are still reproducible with this fix!
